CONFIG_GPIO=y
CONFIG_LOG=y
#CONFIG_BLINK_SLEEP_TIME_MS=1000 #we can also enter the value, or can be entered in the command while build, or we can also change in the menuconfig UI.

#CONFIG_BLINK_SLEEP_250MS=y
